import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Privacy Policy"),
        backgroundColor: Colors.white,
        elevation: 1,
        iconTheme: const IconThemeData(color: Colors.black),
        titleTextStyle: const TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 800),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  "Privacy Policy",
                  style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 16),
                Text(
                  "Last updated: January 1, 2024",
                  style: TextStyle(color: Colors.grey[600]),
                ),
                const SizedBox(height: 32),
                _buildSection("Introduction",
                    "This Privacy Policy applies to the apps and services developed by ZA Developer. We are committed to protecting your privacy."),
                _buildSection("Information Collection and Use",
                    "For our standalone mobile applications, we do not collect, store, or share any personally identifiable information. All data generated by the user remains locally on the device unless explicitly stated otherwise."),
                _buildSection("Log Data",
                    "When you visit our developer website, our hosting provider may collect information that your browser sends whenever you visit a website. This Log Data may include information such as your computer's Internet Protocol ('IP') address, browser version, pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other statistics."),
                _buildSection("Cookies",
                    "Our website may use 'cookies' to collect information and improve our Service. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your computer."),
                _buildSection("Service Providers",
                    "We may employ third-party companies and individuals to facilitate our Service. These third parties may have access to your Personal Information to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose."),
                _buildSection("Security",
                    "We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable."),
                _buildSection("Links to Other Sites",
                    "Our Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites."),
                _buildSection("Children's Privacy",
                    "Our Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13."),
                _buildSection("Contact Us",
                    "If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at support@example.com."),
                const SizedBox(height: 40),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: const TextStyle(fontSize: 16, height: 1.5),
          ),
        ],
      ),
    );
  }
}